// <auto-generated />
using System;
using ColegioSanJose.Models.DB;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ColegioSanJose.Migrations
{
    [DbContext(typeof(ColegioSanJoseContext))]
    partial class ColegioSanJoseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ColegioSanJose.Models.DB.Alumno", b =>
                {
                    b.Property<int>("AlumnoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AlumnoId"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<DateOnly>("FechaNacimiento")
                        .HasColumnType("date");

                    b.Property<string>("Grado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("AlumnoId")
                        .HasName("PK__ALumno__90A6AA135DFE2C43");

                    b.ToTable("ALumno", (string)null);
                });

            modelBuilder.Entity("ColegioSanJose.Models.DB.Expediente", b =>
                {
                    b.Property<int>("ExtpedienteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ExtpedienteId"));

                    b.Property<int>("AlumnoId")
                        .HasColumnType("int");

                    b.Property<int>("MateriaId")
                        .HasColumnType("int");

                    b.Property<decimal>("NotaFinal")
                        .HasColumnType("decimal(4, 2)");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.HasKey("ExtpedienteId")
                        .HasName("PK__Expedien__9C3D3FB0AF769829");

                    b.HasIndex("AlumnoId");

                    b.HasIndex("MateriaId");

                    b.ToTable("Expediente", (string)null);
                });

            modelBuilder.Entity("ColegioSanJose.Models.DB.Materia", b =>
                {
                    b.Property<int>("MateriaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MateriaId"));

                    b.Property<string>("Docente")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("NombreMateria")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.HasKey("MateriaId")
                        .HasName("PK__Materia__0D019DE1BC715C3E");

                    b.ToTable("Materia", (string)null);
                });

            modelBuilder.Entity("ColegioSanJose.Models.DB.Expediente", b =>
                {
                    b.HasOne("ColegioSanJose.Models.DB.Alumno", "Alumno")
                        .WithMany("Expedientes")
                        .HasForeignKey("AlumnoId")
                        .IsRequired()
                        .HasConstraintName("FK__Expedient__Alumn__3B75D760");

                    b.HasOne("ColegioSanJose.Models.DB.Materia", "Materia")
                        .WithMany("Expedientes")
                        .HasForeignKey("MateriaId")
                        .IsRequired()
                        .HasConstraintName("FK__Expedient__Mater__3C69FB99");

                    b.Navigation("Alumno");

                    b.Navigation("Materia");
                });

            modelBuilder.Entity("ColegioSanJose.Models.DB.Alumno", b =>
                {
                    b.Navigation("Expedientes");
                });

            modelBuilder.Entity("ColegioSanJose.Models.DB.Materia", b =>
                {
                    b.Navigation("Expedientes");
                });
#pragma warning restore 612, 618
        }
    }
}
